[features]
seeds = false
skip-lint = false

[programs.localnet]
mint_controller = "SDMCTRx11111111111111111111111111111111111"

[programs.devnet]
mint_controller = "SDMCTRx11111111111111111111111111111111111"

[programs.mainnet]
mint_controller = "SDMCTRx11111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
